[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font.bold]
family = "Inconsolata"

[font.bold_italic]
family = "Inconsolata"

[font.italic]
family = "Inconsolata"

[font.normal]
family = "Inconsolata"
