#!/usr/bin/sh

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if ! xmonad; then
  if xmonad --recompile; then
    xmonad
  fi
fi
