#!/usr/bin/sh

xrdb -merge "$XDG_CONFIG_HOME/.config/X11/xresources"

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if ! xmonad; then
  if xmonad --recompile; then
    xmonad
  fi
fi
