#!/usr/bin/bash

export BROWSER="/usr/bin/firefox"

/usr/bin/feh --bg-tile --no-fehbg "$(/usr/bin/find $HOME/media/wallpapers -type f | /usr/bin/shuf -n 1)"
/usr/bin/xsetroot -cursor_name left_ptr &
/usr/bin/steam &

/usr/bin/openbox
