#!/bin/sh

# Only add to $PATH if not already there
function add_to_path() {
  if ! echo "$PATH" | grep -q "$1"; then
    export PATH="$1:$PATH"
  fi
}
add_to_path "$HOME/bin"
add_to_path "$HOME/bin/scripts"

