#!/usr/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/* ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

/usr/bin/xsetroot -cursor_name left_ptr &
/usr/bin/xbmc
