" daoo's .vimrc

" {{{ Startup
let mapleader=","
source ~/.vim/bundles.vim
" }}}
" {{{ Settings
" moving around, searching and patterns
set ignorecase
set incsearch
set smartcase

" displaying text
set fillchars=vert:│
set lazyredraw
set list
set listchars=tab:▸\ ,extends:❯,precedes:❮
set nowrap
set relativenumber
set scrolloff=5

" syntax, highlighting and spelling
set hlsearch
set cursorcolumn
set cursorline

" multiple windows
set hidden
set laststatus=2

" message and info
set noerrorbells
set novisualbell
set showcmd
set t_vb=

" editing text
set backspace=start,indent,eol
set formatoptions=tcqro
set nojoinspaces
set undolevels=500

" tabs and indenting
set expandtab
set shiftround
set shiftwidth=2
set smarttab
set softtabstop=2

" folding
set foldlevel=0
set foldmethod=indent
set foldnestmax=10
set nofoldenable

" reading and writing files
set autowrite
set backup
set backupdir=~/.vim/tmp//

" the swap file
set directory=/tmp/vim//
set noswapfile

" command line editing
set history=500
set wildmenu
set wildmode=list:longest,full

" other
runtime ftplugin/man.vim
colorscheme mustang
syntax on
" }}}
" {{{ Commands
command! W %!sudo tee > /dev/null %

" Only shown when not in insert mode.
augroup trailing
  au!
  au InsertEnter * :set listchars-=trail:⌴
  au InsertLeave * :set listchars+=trail:⌴
augroup END

function! SwitchSourceHeader()
  let ext = expand("%:e")
  if (ext == "cpp")
    e %:r.hpp
  elseif (ext == "hpp")
    e %:r.cpp
  elseif (ext == "h")
    e %:r.c
  elseif (ext == "c")
    e %:r.h
  endif
endfunction

function! SetSpell(lang)
  setlocal spell
  execute "setlocal spelllang=" . a:lang
  execute "setlocal spellfile=" . "~/.vim/spell/" . matchstr(a:lang, "[a-zA-Z][a-zA-Z]") . "." . &encoding . ".add"
endfunction
" }}}
" {{{ Disabled stupid keys and commands
noremap Q <nop>

" Arrow keys
inoremap <down>  <nop>
inoremap <left>  <nop>
inoremap <right> <nop>
inoremap <up>    <nop>
noremap  <down>  <nop>
noremap  <left>  <nop>
noremap  <right> <nop>
noremap  <up>    <nop>

inoremap <c-left>  <nop>
inoremap <c-right> <nop>
noremap  <c-left>  <nop>
noremap  <c-right> <nop>

" Above arrow keys
inoremap <del>      <nop>
inoremap <end>      <nop>
inoremap <home>     <nop>
inoremap <pagedown> <nop>
inoremap <pageup>   <nop>
noremap  <del>      <nop>
noremap  <end>      <nop>
noremap  <home>     <nop>
noremap  <pagedown> <nop>
noremap  <pageup>   <nop>
" }}}
" {{{ Key bindings
" F-keys
nnoremap <f5> :make run<cr>
nnoremap <f8> :silent! :make \| :redraw! \| :botright :cw<cr>
nnoremap <f9> :make ctags<cr>
nnoremap <f10> :make lint<cr>

" Tabular and clean up
nnoremap <leader>ae :let @"=@/<cr>:%s/\s\+$//<cr>:let @/=@"<cr>
nnoremap <leader>aj wby0o<esc>pVr J
nnoremap <leader>ap {jV}k:sort<cr>
nnoremap <leader>as :%s/( /(/g<cr>:%s/ )/)/g<cr>

" Misc
inoremap <c-space> <c-x><c-o>
nnoremap <leader>cd :cd %:p:h<cr>
nnoremap <leader>cp :%y+<cr>
nnoremap <leader>ef :e %<cr>
nnoremap <leader>eve :vsplit $MYVIMRC<cr>
nnoremap <leader>evs :source $MYVIMRC<cr>
nnoremap <leader>h :call SwitchSourceHeader()<cr>
nnoremap <leader>dt :diffthis<cr>
nnoremap <leader>du :diffupdate<cr>
nnoremap <leader>do :diffoff!<cr>
nnoremap <leader>se :call SetSpell("en_us")<cr>
nnoremap <leader>ss :call SetSpell("sv")<cr>
nnoremap <leader>so :setlocal nospell<cr>
nnoremap K kJ
vnoremap <c-b> c<c-r>=<c-r>"<cr><esc>
vnoremap <c-x> y`]a = <c-r>=<c-r>"<cr><esc>

" Searching
nnoremap <leader>fc :nohlsearch<cr>
nnoremap <leader>fl /<c-r>=expand("<cword>")<cr><cr>
nnoremap <leader>fr :%s@<c-r>=expand("<cword>")<cr>@
vnoremap <leader>fr y:%s@<c-r>"@

nnoremap N Nzz
nnoremap n nzz

" Saving
noremap <c-s> :w<cr>
inoremap <c-s> <esc>:w<cr>a

" Split/tabs navigation
nnoremap <c-s-tab> :tabprevious<cr>
nnoremap <c-tab> :tabnext<cr>
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
" }}}

" vim: fdm=marker :
