#!/usr/bin/env bash

function clean_md5sum() {
  cut -d ' ' -f 1
}

function md5sum_only() {
  md5sum "$1" | clean_md5sum
}

function md5sum_dir() {
  tar c "$1" 2> /dev/null | md5sum | clean_md5sum
}

