#!/usr/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/* ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export BROWSER="/usr/bin/firefox"

xrdb -merge "$HOME/.Xresources"

/usr/bin/xsetroot -cursor_name left_ptr
/usr/bin/dex --autostart
/usr/bin/pcmanfm --desktop --one-screen &
/usr/bin/pcmanfm --set-wallpaper="$(/usr/bin/find $HOME/media/wallpapers -type f | /usr/bin/shuf -n 1)" --wallpaper-mode=center
/usr/bin/steam &

exec /usr/bin/openbox
