#!/usr/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/* ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export BROWSER=/usr/bin/qutebrowser

xrdb -merge "$HOME/.Xresources"

/usr/bin/systemctl --user import-environment BROWSER

/usr/bin/systemctl --user start \
  compton \
  nvidia-settings \
  pointer \
  unclutter \
  wallpaper

exec /usr/bin/xmonad
