#!/usr/bin/env bash

rnd() {
  echo `</dev/urandom tr -dc A-Za-z0-9 | head -c16`
}

# Check for atool
if ! atool=$(which atool) 2> /dev/null; then
  echo "atool not found" >&2
  exit 1
fi

# Check parameters
file="$@"
repack=1

if [[ -a $file ]]; then
  # Some basic information about the archive
  name="$(basename "$file")"
  archive=$(readlink -f "$file")
  dir="$(dirname "$(readlink -f "$file")")"

  echo "Extracting..."
  # Extract to a tmp dir
  tmpdir=`mktemp -d "/tmp/aedit-XXXXXXXX"`
  $atool --extract-to=$tmpdir "$@"

  echo "Launching shell..."
  # Start a new shell in the tmp directory
  cd "$tmpdir"
  $SHELL

  if [[ $repack ]]; then
    echo "Repacking..."
    mv "$archive" "/tmp/$name.`rnd`" # Backup
    $atool -a -f "$archive" $(ls -b $tmpdir)
  fi

  echo "Done."
  rm -r "$tmpdir"
  cd "$dir"
else
  echo "File '$file' does not exist." >&2
fi
