#!/usr/bin/env bash

mute() {
  amixer -q set Master mute
}

unmute() {
  amixer -q set Master unmute
}

mutefile="/tmp/alsa-mute"

if [[ $(cat $mutefile) = "0" ]]; then
  mute
  echo "1" > $mutefile
else
  unmute
  echo "0" > $mutefile
fi
