#!/usr/bin/env ruby

DEFAULT_BLINKS = 5
DEFAULT_DELAY  = 1

blinks = ARGV[0] ? ARGV[0].to_i : DEFAULT_BLINKS
delay  = ARGV[1] ? ARGV[1].to_f : DEFAULT_DELAY

blinks.times do
  system("xset led on")
  sleep(delay)
  system("xset led off")
  sleep(delay)
end

