#!/usr/bin/env bash

# A shortcut function that simplifies usage of xclip.
# - Accepts input from either stdin (pipe), or params.
# - If the input is a filename that exists, then it
#   uses the contents of that file.
# ------------------------------------------------

color_green='\e[0;32m'
color_red='\e[1;31m'
color_yellow='\e[0;33m'
color_reset='\e[0m'

if ! type xclip > /dev/null 2>&1; then
  echo -e "${color_red}You must have the 'xclip' program installed.$color_reset"
elif [[ $USER == "root" ]]; then
  echo -e "${color_red}Must be regular user (not root) to copy a file to the clipboard.$color_reset"
else
  if [[ "$(tty)" == "not a tty" ]]; then
    input="$(< /dev/stdin)"
  else
    input="$*"
  fi

  if [[ -z $input ]]; then
    echo "Copies a string or the contents of a file to the clipboard."
    echo "Usage: cb <string or file>"
    echo "       echo <string or file> | cb"
  else
    if [[ -e $input ]]; then
      input="$(< $input)"
    fi

    echo -n "$input" | xclip -selection c
    if (( ${#input} > 80 )); then
      input="$(echo $input | cut -c1-80)$color_yellow...$color_reset"
    fi

    echo -e "${color_green}Copied to clipboard:$color_reset $input"
  fi
fi

