#!/usr/bin/env bash

if [[ -z "$DISPLAY" ]]; then
  echo "No X server running."
  exit 1
fi

if ! type xclip > /dev/null 2>&1; then
  echo "You must have the 'xclip' program installed."
  exit 1
fi

if [[ $USER == "root" ]]; then
  echo "Must be regular user (not root) to copy a file to the clipboard."
fi

if [[ -z $* ]]; then
  data="$(< /dev/stdin)"
else
  input="$*"

  if [[ -e "$input" ]]; then
    data="$(< $input)"
  else
    data="$input"
  fi
fi

if [[ -z $data ]]; then
  echo "Copies a string or the contents of a file to the clipboard."
  echo "Usage: cb <string or file>"
  echo "       echo <string or file> | cb"
  exit 1
else
  echo -n "$data" | xclip -selection c
  if (( ${#data} > 80 )); then
    output="$(echo $data | cut -c1-80)"
  else
    output="$data"
  fi

  echo -e "Copied to clipboard: $output"
fi
