#!/usr/bin/env ruby
#
# Run the dropbox until everything is in sync, then shut down.
#

def dropbox_status()
  return `dropbox status`.chomp
end

def is_idle(status)
  return status == "Up to date"
end

def wait_for_idle(delta)
  while not is_idle(dropbox_status()) do
    sleep(delta)
  end
end

if is_idle(dropbox_status())
  exit 0
end

system("dropbox start")

wait_for_idle(1)
sleep(2)
wait_for_idle(2)

system("dropbox stop")
