#!/usr/bin/env bash

# Episodes
# By Daniel Oom

# TODO: custom command
command="mplayer"
state_file="./.episodes-state"

function init() {
  if [ -f "$state_file" ]; then
    echo "Already initialized."
    exit 1
  else
    echo "Initializing..."
    ls > $state_file

    echo "Found $(cat $state_file | wc -l) file(s)"

    echo "Done"
    exit 0
  fi
}

function remove() {
  if [ -f "$state_file" ]; then
    echo "Okay."
    rm $state_file
    exit 0
  else
    echo "Not initialized"
    exit 0
  fi
}

case "$1" in
  --init)   init ;;
  --remove) remove ;;
esac

if [ -f "$state_file" ]; then
  # Backup and get state
  cp $state_file $state_file.bak

  quit=0
  while [ $quit -ne 1 -a -s $state_file ]; do
    file=$(head -n1 $state_file)

    echo "$file"
    if $command $file &> /dev/null; then
      echo -n "Remove file from state [y,q]? "

      inp=""
      read inp

      case "$inp" in
        'y'|'Y') sed -i 1d $state_file ;;
        'q'|'Q') quit=1 ;;
      esac
    fi
  done
else
  echo "Directory need to be initialized."
  echo "Run episodes --init"
fi
