#!/usr/bin/env ruby

require 'set'
require 'find'

dir  = "."
exts = Set.new()

Find.find(dir) do |path|
  if not File.directory?(path)
    ext = File.extname(path)
    if (not ext.empty?) and (not exts.include?(ext))
      exts << ext
      puts ext
    end
  end
end

