#!/usr/bin/env bash

ghc -Wall \
  -fno-warn-unused-do-bind \
  -fwarn-duplicate-exports \
  -fwarn-hi-shadowing \
  -fwarn-incomplete-patterns \
  -fwarn-lazy-unlifted-bindings \
  -fwarn-missing-fields \
  -fwarn-missing-methods \
  -fwarn-missing-signatures \
  -fwarn-monomorphism-restriction \
  -fwarn-name-shadowing \
  -fwarn-orphans \
  -fwarn-overlapping-patterns \
  -fwarn-tabs \
  -fwarn-type-defaults \
  -fwarn-unused-binds \
  -fwarn-unused-imports \
  -fwarn-unused-matches \
  -fwarn-wrong-do-bind \
  $@
