#!/usr/bin/env bash

color_red='\e[0;31m'
color_green='\e[0;32m'
text_reset='\e[0m'

command=$1

if [[ -z $command || ($command != "push" && $command != "pull") ]]; then
  echo "Usage: git-command (push|pull)"
  exit 1
fi

for repo in $(cat "$HOME/.git-repos"); do
  cd "$HOME/$repo"
  if [[ -z "$(git status --porcelain)" ]]; then
    echo -en "${color_green}${command}ing $repo\n"
    git $command &> /dev/null
  else
    echo -en "${color_red}not ${command}ing $repo\n"
  fi
done

echo -en $text_reset
