#!/usr/bin/env ruby

def md5sum(file)
  return `md5sum #{file}`[0, 32]
end

File.open("#{ENV["HOME"]}/.git-repos") do |f|
  while (line = f.gets)
    repo = line.chomp
    puts "Syncing #{repo}"

    dir        = File.join(ENV["HOME"], repo)
    git_dir    = File.join(dir, ".git/")
    fetch_head = File.join(git_dir, "FETCH_HEAD")
    
    old = md5sum(fetch_head)
    system("git --git-dir=#{git_dir} fetch --quiet")
    new = md5sum(fetch_head)
    if old != new
      puts "MERGE ALERT!"
      #`#{ENV["SHELL"]}`
    end
  end
end
