#!/usr/bin/env ruby

TEXT_RESET       = "\e[0m"
TEXT_RED         = "\e[0;31m"
TEXT_PURPLE      = "\e[0;35m"
TEXT_YELLOW_BOLD = "\e[1;33m"

def puts_color(color, str)
  puts "#{color}#{str}#{TEXT_RESET}"
end

def md5sum(file)
  return `md5sum #{file}`[0, 32]
end

silent = false
case ARGV[0]
  when "-q", "--quiet"
    silent = true
end

File.open("#{ENV["HOME"]}/.git-repos") do |f|
  while (line = f.gets)
    repo = line.chomp
    puts_color(TEXT_PURPLE, "Syncing #{repo}")

    dir        = File.join(ENV["HOME"], repo)
    git_dir    = File.join(dir, ".git/")
    fetch_head = File.join(git_dir, "FETCH_HEAD")
    
    old = md5sum(fetch_head)
    if not system("git --git-dir=#{git_dir} fetch --quiet")
      puts_color(TEXT_RED, "Error while running fetch")
      exit 1
    end

    if not silent
      new = md5sum(fetch_head)
      if old != new
        puts_color(TEXT_YELLOW_BOLD, "Fetch resulted in new HEAD")
        puts_color(TEXT_YELLOW_BOLD, "Opening #{ENV["SHELL"]} in #{dir}")
        system("cd #{dir} && #{ENV['SHELL']}")
      end
    end
  end
end
