#!/bin/bash

command="ping 192.168.0.1 -c 2"

i=0
while [ $i -lt 5 ]; do
  $command > /dev/null
  if $command > /dev/null; then
    for e in $*; do
      eval $e
    done

    exit 0
  fi

  sleep 15
  i=$(expr $i + 1)
done

exit 1
