#!/usr/bin/env bash

command="ping 192.168.0.1 -c 2"

sleep_time=5
sleep_delta=5
i=0
while [[ $i -lt 6 ]]; do
  $command > /dev/null
  if $command > /dev/null; then
    while [[ $# -ne 0 ]]; do
      exec $1 &
      shift
    done

    exit 0
  fi

  sleep $sleep_time

  let "sleep_time += $sleep_delta"
  let "i++"
done

exit 1
