#!/usr/bin/env bash

device="$1"
dir="$2"
workgroup="$3"
user="$4"

if [[ -z "$device" || -z "$dir" || -z "$workgroup" || -z "$user" ]]; then
  echo "Usage: samba-mount DEVICE DIR WORKGROUP USER"
  echo "Example: samba-mount host:share /media/network MYWORKGROUP myuser"
  exit 1
elif [[ ! -d "$dir" ]]; then
  echo "Error: \"$dir\" is not a directory."
  exit 1
fi

echo "Mounting $device at $dir..."
echo "Logging in as $workgroup\\$user"

mount -t cifs \
  -o user="$user",workgroup="$workgroup",rw,uid=daniel,gid=users \
  "$device" "$dir"
