#!/bin/sh

MPC="/usr/bin/mpc"
MPD="/usr/bin/mpd $HOME/.mpd/mpd.conf"

$MPC status > /dev/null
if [ $? -eq 0 ]; then
  # MPD running
  $MPC toggle > /dev/null
else
  $MPD > /dev/null
  $MPC play > /dev/null
fi

