#!/bin/bash

mpd_dir="$HOME/.mpd"
mpc="mpc -q"
mpd="mpd $mpd_dir/mpd.conf"

if [ -f "$mpd_dir/pid" ]; then
  # mpd running
  $mpc toggle
else
  $mpd
  sleep 1 # Sleep a second to let mpd start
  $mpc play
fi

