#!/usr/bin/env bash

mpd_dir="$HOME/.mpd"
playlist_dir="$mpd_dir/playlists"

for m3u in $playlist_dir/*.m3u; do
  if [[ -f "$m3u" ]]; then
    echo "Sorting $(basename "$m3u")"
    sort -u "$m3u" -o "$m3u"
  fi
done

