#!/usr/bin/env bash

url="ftp://goes.gsfc.nasa.gov/pub/goescolor/goeseast/overview2/color_lrg/latestfull.jpg"
file="/tmp/nasa-image-latest-full.jpg"

curl "$url" -o "$file"

# Remove text from image
convert "$file" \
  -fill black \
  -draw "rectangle 0, 0 750,50" \
  "$file"

feh --bg-max "$file"
