#!/usr/bin/env bash

if [[ $# -ge 1 ]]; then
  cd $HOME
  tmpgame="$(mktemp)"
  DISPLAY=:1.0
  echo -e "openbox &\nsetxkbmap dvpse\n$*" > "$tmpgame"
  xinit "$tmpgame" -- :1 -xf86config .xorg-game.conf || exit 1
  rm -f "$tmpgame"
else
  echo "not a valid argument"
fi
