#!/usr/bin/env bash

for dir in ~/.mozilla/firefox/*.*/; do
  if [ -d "$dir" ]; then
    echo
    echo "$dir"
    cd "$dir"
    for file in ./*.sqlite; do
      if [ -f "$file" ]; then
        echo "$file"
        sqlite3 "$file" vacuum
        sqlite3 "$file" reindex
      fi
    done
  fi
done
