#!/usr/bin/env bash

list() {
  pacmd list-$1 | grep index | awk -F': ' '{print $2}'
}

mute() {
	pacmd set-$1-mute $2 1 > /dev/null
}

unmute() {
	pacmd set-$1-mute $2 0 > /dev/null
}

statusfile="/tmp/pa-mute"

if [ "`cat $statusfile`" = "0" ]; then
  action=mute
  echo "1" > $statusfile
else
  action=unmute
  echo "0" > $statusfile
fi

# Sinks
for s in `list sinks`; do
  $action sink $s
done

# Sources
for s in `list sources`; do
  $action source $s
done

