#!/usr/bin/env bash
#
# A script that selects a new random wallpaper and creates a link for it.
# By daoo
#

if [[ ! -d "$1" ]]; then
  echo "$1 not a directory."
  exit 1
fi

wallpaper_dir="$1"
wallpaper_link="$HOME/.wallpaper"

# We assume that all files in the wallpaper dir are images
file=$(find "$wallpaper_dir" -type f | shuf -n 1)

ln -fs "$file" "$wallpaper_link"
