#!/usr/bin/env bash

if [[ -d ".cabal-sandbox" ]]; then
  dbflag="-package-db=$(echo .cabal-sandbox/*-packages.conf.d)"
else
  dbflag=""
fi

ghc \
  -o /tmp/Main \
  -outputdir /tmp \
  -isrc \
  $dbflag \
  -fforce-recomp \
  -dsuppress-coercions \
  -dsuppress-module-prefixes \
  -dsuppress-uniques \
  -dsuppress-idinfo \
  -dsuppress-type-applications \
  -dppr-cols270 \
  -dppr-case-as-let \
  -ddump-${TYPE-simpl} \
  $@ \
  | vim "+setf haskell" -
