#!/usr/bin/env bash

set -e

# TODO: predictable temp dir

if [[ -d ".cabal-sandbox" ]]; then
  dbflag="-package-db=$(echo .cabal-sandbox/*-packages.conf.d)"
else
  dbflag=""
fi

tmpdir="$(mktemp -d)"

${GHC:-ghc} \
  -o "$tmpdir/main" \
  -outputdir "$tmpdir" \
  -isrc \
  "$dbflag" \
  -dsuppress-coercions \
  -dsuppress-module-prefixes \
  -dsuppress-uniques \
  -dsuppress-idinfo \
  -dsuppress-type-applications \
  -dppr-cols270 \
  -dppr-case-as-let \
  -ddump-to-file \
  -ddump-simpl \
  "$@"

( cd "$tmpdir"; ${EDITOR:-nvim} )

rm -rf "$tmpdir"
