#!/usr/bin/env bash

file="$1"
if [[ -f "$file" ]]; then
  base="$(basename "$file")"
  tmp="$(mktemp "/tmp/$base-XXXXXXXX")"

  cp "$file" "$tmp"
  strip -s "$tmp"
  objdump -dCM intel "$tmp" > "$tmp.asm"
  vim "$tmp.asm"

  rm -f "$tmp" "$tmp.asm"
fi
