#!/usr/bin/env bash

if [[ -d "cabal-dev" ]]; then
  dbflag="-package-db=$(echo cabal-dev/packages-*.conf)"
else
  dbflag=""
fi

ghc \
  -o /tmp/Main \
  -outputdir /tmp \
  -isrc \
  $dbflag \
  -fforce-recomp \
  -dsuppress-coercions \
  -dsuppress-module-prefixes \
  -dsuppress-uniques \
  -dsuppress-idinfo \
  -dsuppress-type-applications \
  -dppr-cols270 \
  -dppr-case-as-let \
  -ddump-simpl \
  $@ \
  | vim "+setf haskell" -
