#!/usr/bin/env ruby

require "fileutils"

require_relative "./minecraft.rb"

class Server
  def initialize(jar)
    @jar = jar
  end

  def run(config, world)
    FileUtils.ln_sf(world, config)
    system("sed -i 's/level-name=.*/level-name=#{File.basename(world)}/' '#{File.join(config, 'server.properties')}'")
    system("cd #{config} && java #{Minecraft::JAVAOPTS} -jar #{@jar} nogui")
  end
end

diagJar = SelectFileDialog.new(
  "Select Jar",
  Minecraft::SERVER_JARS_DIR,
  lambda { |f| "nothing here yet" }
)
diagJar.run()
if not diagJar.get_exit()
  exit 0
end
jar = diagJar.get_result()

diagConfig = SelectFileDialog.new(
  "Select Config",
  Minecraft::SERVER_CONFIGS_DIR,
  lambda { |f| File.read(File.join(f, "description.txt")) }
)
diagConfig.run()
if not diagConfig.get_exit()
  exit 0
end

config = diagConfig.get_result()

diagWorld = SelectFileDialog.new(
  "Select World",
  Minecraft::SERVER_WORLDS_DIR,
  lambda do |f|
    df = File.join(f, "description.txt")
    if File.exists?(df)
      return File.read(df)
    else
      return "no description"
    end
  end
)
diagWorld.run()
if not diagWorld.get_exit()
  exit 0
end

world = diagWorld.get_result()

server = Server.new(jar)
server.run(config, world)
