#!/usr/bin/env ruby

require_relative "./minecraft.rb"

def run(jar, opts)
  if File.exists?(Minecraft::JAR_FILE)
    puts "Backing up first..."
    File.rename(Minecraft::JAR_FILE, Minecraft::JAR_BACKUP_FILE)
  end

  puts "Putting new jar in place..."
  FileUtils.cp(jar, Minecraft::JAR_FILE)

  start_time = Time.now()
  puts "Launching minecraft at #{start_time}"

  Utils.run_launcher()

  end_time = Time.now()
  puts "Minecraft closed at #{end_time}"

  puts "Cleaning up..."
  FileUtils.rm_f(Minecraft::JAR_FILE)

  if File.exists?(Minecraft::JAR_BACKUP_FILE)
    FileUtils.mv(Minecraft::JAR_BACKUP_FILE, Minecraft::JAR_FILE)
  end

  puts "You have been playing for #{Utils.seconds_to_str(end_time - start_time)}"
end

diagJar = SelectFileDialog.new(
  "Select Jar",
  Minecraft::CLIENT_JARS_DIR,
  lambda { |f| "nothing here yet" }
)
diagJar.run()
if not diagJar.get_exit()
  exit 0
end
jar = diagJar.get_result()

run(jar, Minecraft::JAVAOPTS)

# vim: set fdm=marker :
