#!/usr/bin/env bash

minecraft_dir="$HOME/games/minecraft/server"
server_jar="$minecraft_dir/minecraft_server.jar"

javaopts="-server -Xmx1024M -Xms512M"
command="java $javaopts -jar $server_jar nogui"

function desc() {
  local df="$1/description.txt"
  if [[ -f "$df" ]]; then
    cat "$df"
  else
    echo "No description availible"
  fi
}

function menu() {
  local i=0
  for f in $1/*; do
    if [[ -d $f ]]; then
      servers[$i]=$(basename "$f")
      let i++
      servers[$i]=$($2 $f)
      let i++
    fi
  done

  dialog --menu "Choose server:" 0 60 15 "${servers[@]}"
}

function launch() {
  # Assume these exists
  local server="$1"
  local world="$2"

  local server_dir="$minecraft_dir/servers/$server"

  # Create link
  ln -fsn "$minecraft_dir/worlds/$world" "$server_dir/$world"

  # Set world name
  sed -i "s/level-name=.*/level-name=$world/" "$server_dir/server.properties"
  
  cd "$server_dir"
  $command
}

menu "$minecraft_dir/servers" desc 2> "/tmp/server.ans"
if [[ $? -ne 0 ]]; then
  exit 1
fi
server=$(cat "/tmp/server.ans")

menu "$minecraft_dir/worlds" desc 2> "/tmp/world.ans"
if [[ $? -ne 0 ]]; then
  exit 1
fi
world=$(cat "/tmp/world.ans")

launch "$server" "$world"
