#!/bin/bash

minecraft_dir=$HOME/games/minecraft/client
minecraft_jar=$minecraft_dir/minecraft.jar

javaopts="-server -Xmx1024M -Xms512M"

cd "$minecraft_dir"

_JAVA_AWT_WM_NONREPARENTING=1 \
java $javaopts -cp $minecraft_jar net.minecraft.LauncherFrame

