#!/bin/zsh

# PS1 and Title
if [ "$SSH_CLIENT" != "" ]; then
  # Connected through ssh
  PS1='%n@%m:%~$ '
else
  PS1='%n:%~$ '
fi

case "$TERM" in
  xterm*|*rxvt*)
    # Set the title
    precmd () {print -Pn "\e]0;%n@%m: %~\a"}
  ;;
esac

# History
HISTFILE=~/.zhistory
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt histignoredups
setopt incappendhistory

# Stuff
setopt nobeep
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'
export EDITOR="vim"
export PAGER="less"
export LESS="-F -i -X -r"

# Only add ~/bin/ to $PATH if not already there
echo "$PATH" | grep -q "$HOME/bin"
if [ $? -ne 0 ]; then
  export PATH="$HOME/bin/:$PATH"
fi

