#!/bin/zsh

chalmers() {
  TERM=linux ssh lalti@remote$(($RANDOM % 4 + 1)).student.chalmers.se $*
}

f() {
  find . -iname "*$@*"
}

ff() {
  find . -iname "*$@*" -not -type d
}

# z.sh
if [[ -f ~/dotfiles/zsh/plugins/z/z.sh ]]; then
  . ~/dotfiles/zsh/plugins/z/z.sh
  function precmd () {
    z --add "$(pwd -P)"
  }
fi

