#!/bin/zsh

chalmers() {
  TERM=linux ssh lalti@remote$(($RANDOM % 4 + 1)).student.chalmers.se $*
}

f() {
  find . -iname "*$@*"
}

ff() {
  find . -iname "*$@*" -not -type d
}

db-share() {
  file_name=$(basename "$1")
  file_path="/storage/dropbox/Public/$file_name"
  cp "$1" "$file_path"
  
  dropbox puburl "$file_path"
}
