#!/bin/zsh

# Skip all this for non-interactive shells
[ -z "$PS1" ] && return

# {{{ Config
# PS1
if [ -z "$SSH_CLIENT" ]; then
  # Not connected through ssh
  PS1="$USER:%~$ "
else
  PS1="$USER@$HOST:%~$ "
fi

# Title
case "$TERM" in
  xterm*|*rxvt*)
    # Set the title
    precmd () {print -Pn "\e]0;%~ (%n@%m)\a"}
  ;;
esac

# History
HISTFILE=~/.zhistory
HISTSIZE=100000
SAVEHIST=100000
setopt appendhistory
setopt histignoredups
setopt incappendhistory

# Stuff
setopt nobeep
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'
export EDITOR="vim"
export PAGER="less"
export LESS="-FiXr"

# Disable ctrl-q and ctrl-s
stty -ixon
# }}}
# {{{ Aliases
# Give some commands fancy colors
alias grep='grep --color=auto'
alias ls='ls -h -F --color=auto'
alias tree='tree -C'
alias pacman='pacman-color'

# Some for ls
alias l='ls'
alias ll='ls -lh'
alias la='ls -a'
alias lla='ls -lha'

# Up up and away
alias '..'='cd ..'
alias '...'='cd ../..'
alias '....'='cd ../../..'
alias '.....'='cd ../../../..'

# Bazinga
alias :q='echo you are not in vim anymore'
alias :w='echo you are not in vim anymore'

# Other
alias bell="echo -e '\a'"
alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"
alias calc='noglob calc'
alias g='git'
alias y='yaourt'
# }}}
# {{{ Binds
bindkey '' history-search-backward
bindkey '' history-search-forward
bindkey '' history-incremental-search-backward
bindkey '' push-line
# }}}
# {{{ Autocompletion
# Completion
autoload -U compinit
compinit
zstyle ':completion:*' special-dirs true

if [ -f "/etc/zsh_command_not_found" ]; then
  . /etc/zsh_command_not_found
fi
# }}}
# {{{ Local settings
if [ -f ~/.zlocal ]; then
  . ~/.zlocal
fi
# }}}

# vim: fdm=marker :
