#!/usr/bin/env perl

sub copy_selection {
  my ($self) = @_;

  open (my $pipe,'|-','xclip -selection clipboard') or die;
  print $pipe $self->selection;
  close $pipe;

  ()
}

sub paste_clipboard {
  my ($self) = @_;

  my $clipboard = `xclip -o -selection clipboard`
    or die 'Could not read clipboard';

  $self->tt_write($self->locale_encode($clipboard));
  ()
}

sub on_user_command {
  my ($self, $cmd) = @_;

  if ($cmd eq 'copy-pasta:copy') {
    copy_selection($self);
  } elsif ($cmd eq 'copy-pasta:paste') {
    paste_clipboard($self);
  }

  ()
}
